---
# ansible-playbook site.yaml --extra-vars='playbook_hosts=localhost'
- name: deploy dotfiles using GNU Stow
  hosts: "{{ playbook_hosts | default('localhost') }}"
  vars:
    stow_packages: ["bash", "git", "vim", "dotsh"]
    stow_keep_dirs:
      - "{{ ansible_env.HOME }}/.config/git"
      - "{{ ansible_env.HOME }}/.ssh/config.d"
      - "{{ ansible_env.HOME }}/bin"
    stow_find_dirs:
      - "{{ ansible_env.HOME }}/.ssh"
      - "{{ ansible_env.HOME }}/bin"

  roles:
    - ansible_stow
